name: cdl_pro
description: "CDL Pro is a quiz-based app to help you prepare for the CDL exam with interactive tests and explanations."
publish_to: "none"

version: 1.0.22+45

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^9.2.1
  flutter_svg: ^2.3.0
  flutter_bloc: ^9.1.1
  equatable: ^3.0.0
  dio: ^5.11.1
  translator: ^1.0.4
  intl: ^0.20.3
  talker_flutter: ^5.1.20
  firebase_core: 4.15.0
  auto_route: ^11.1.0
  talker_dio_logger: ^5.1.20
  talker_bloc_logger: ^5.1.20
  easy_localization: ^3.0.8
  flutter_launcher_icons: ^0.14.4
  flutter_staggered_animations: ^1.1.1
  flutter_screenutil: ^5.9.3
  firebase_database: ^12.6.0
  google_fonts: ^8.2.1
  cloud_firestore: ^6.10.0
  shared_preferences: ^2.5.5

  flutter_hooks: ^0.21.3
  lottie: ^3.6.1
  dropdown_button2: ^3.1.0


  flutter_native_splash: ^2.4.8
  firebase_auth: 6.7.0
  google_sign_in: ^7.2.0
  email_validator: ^3.0.0
  cryptography: ^2.9.0
  flutter_secure_storage: ^11.2.0
  sign_in_with_apple: ^8.2.0
  animated_text_kit: ^4.3.0
  top_snackbar_flutter: ^3.4.0
  in_app_purchase: ^3.3.1
  in_app_purchase_android: ^0.5.3
  in_app_purchase_storekit: ^0.4.13
  url_launcher: ^6.3.2
  package_info_plus: ^10.2.1

  sqflite: ^2.4.4
  path: ^1.9.1
  introduction_screen: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.14.1
  auto_route_generator: ^10.6.0
  build_runner: ^2.16.1

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/svgs/
    - assets/lottie/
    - assets/icons/
    - assets/DB/tests/
    - assets/DB/tests_ru/
    - assets/DB/tests_uk/
    - assets/DB/tests_es/
    - assets/DB/road_signs/
    - assets/DB/trip_inspection/
    - assets/DB/terms_of_use/
    - assets/DB/privacy_policy/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/truck_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/truck.png"
  android: true
  ios: true
  web: false

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
